### ISSUE TITLE
与angularjs不能配合使用

### ISSUE THREAD

**Issue by julor** [frozenui/frozenjs#11]
由于Frozenjs阻止了click事件，导致所有的angularjs的data-ng-click都无法响应

**Comment by fayching** [comment]
具体是用哪个组件？

**Comment by hahnzhu** [comment]
麻烦提供个 Demo

**Comment by julor** [comment]
@fayching 使用tab组件

**Comment by fayching** [comment]
我今天也遇到这个问题了 :flushed:  还有tab里面的内容滚不动

**Comment by hahnzhu** [comment]
@julor click/tap 无法响应问题已修复，请使用最新代码 [frozenjs](https://raw.githubusercontent.com/frozenui/frozenjs/master/1.0.1/frozen.js)
