### ISSUE TITLE
dialog回调不会被调用

### ISSUE THREAD

**Issue by manageryzy** [frozenui/frozenjs#26]
版本就是1.0.1，代码如下。

                $.dialog({
                    title: sms.title ,
                    content: sms.message ,
                    button: ['确定', '删除'] ,
                    callback: function (i) {
                        alert(i);
                        sms.hasDeleted = true;
                        user.save();
                        $(dom).remove();
                    },
                    end:function(i){
                        alert(i)
                    }
                });

两个回调函数都没有被触发

**Comment by fayching** [comment]
是通过这种方式
dia.on("dialog:action",function(e){
        console.log(e.index)
    });

**Comment by manageryzy** [comment]
OK，多谢。issue可以关闭了么了呢
